import { UserRole, UserProfile, SupportedLanguage } from "../types";

export interface AppState {
  currentRole: UserRole;
  currentProfile: UserProfile;
  language: SupportedLanguage;
  offlineSimulated: boolean; // Demo toggle for offline mode testing
  demoModeActive: boolean;
}

const DEFAULT_PROFILES: Record<UserRole, UserProfile> = {
  FARMER: {
    id: "user-farmer-01",
    name: "Ramesh Patil",
    organization: "Pune Organic Farmers Producer Co.",
    email: "ramesh.patil@agripune.in",
    phone: "+91 98220 11223",
    role: "FARMER",
    address: "At Post Khed, Farm No. 42",
    district: "Pune",
    state: "Maharashtra",
    pinCode: "410505",
    fssaiNumber: "11521034000189",
    verified: true,
  },
  PROCESSOR: {
    id: "user-processor-01",
    name: "Sunil Deshmukh",
    organization: "Sahyadri Agro Processing Hub",
    email: "sunil@sahyadrifoods.co.in",
    phone: "+91 98900 44556",
    role: "PROCESSOR",
    address: "Plot 88, MIDC Bhosari",
    district: "Pune",
    state: "Maharashtra",
    pinCode: "411026",
    fssaiNumber: "10019022009812",
    gstNumber: "27AABCS1234F1Z1",
    verified: true,
  },
  DISTRIBUTOR: {
    id: "user-distributor-01",
    name: "Vikram Shah",
    organization: "Western India FMCG Logistics",
    email: "vikram@westernfmcg.in",
    phone: "+91 98201 66778",
    role: "DISTRIBUTOR",
    address: "Bhiwandi Warehousing Hub, Complex 4",
    district: "Thane",
    state: "Maharashtra",
    pinCode: "421302",
    fssaiNumber: "11519011000888",
    verified: true,
  },
  WAREHOUSE: {
    id: "user-warehouse-01",
    name: "Mahesh Joshi",
    organization: "Maharashtra State Cold Storage Facility",
    email: "m.joshi@mscoldstorage.gov.in",
    phone: "+91 98230 77889",
    role: "WAREHOUSE",
    address: "Central Cold Storage, Panvel",
    district: "Raigad",
    state: "Maharashtra",
    pinCode: "410206",
    fssaiNumber: "10018021000456",
    verified: true,
  },
  TRANSPORTER: {
    id: "user-transporter-01",
    name: "Suresh Pawar",
    organization: "Maha Express Cold Logistics",
    email: "suresh@mahaexpress.in",
    phone: "+91 98500 88990",
    role: "TRANSPORTER",
    address: "Reefer Fleet Terminal, Chakan",
    district: "Pune",
    state: "Maharashtra",
    pinCode: "410501",
    fssaiNumber: "11520033000567",
    verified: true,
  },
  RETAILER: {
    id: "user-retailer-01",
    name: "Priya Sharma",
    organization: "NatureFresh Supermarket",
    email: "priya@naturefreshstores.in",
    phone: "+91 98190 22334",
    role: "RETAILER",
    address: "Panchpakhadi, Near Talao Pali",
    district: "Thane",
    state: "Maharashtra",
    pinCode: "400602",
    fssaiNumber: "11521010000321",
    gstNumber: "27AAACN5678E1Z5",
    verified: true,
  },
  CONSUMER: {
    id: "user-consumer-01",
    name: "Aarti Kulkarni",
    organization: "Public Consumer",
    email: "aarti.k@gmail.com",
    phone: "+91 98210 99887",
    role: "CONSUMER",
    address: "Dadar West, Mumbai",
    district: "Mumbai City",
    state: "Maharashtra",
    pinCode: "400028",
    verified: true,
  },
  AUTHORITY: {
    id: "auth-fssai-01",
    name: "Dr. K. V. Ramanathan",
    organization: "Food Safety and Standards Authority of India (FSSAI)",
    email: "inspector.mumbai@fssai.gov.in",
    phone: "+91 22 2654 3210",
    role: "AUTHORITY",
    address: "FSSAI Western Regional Office, BKC, Mumbai",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    pinCode: "400051",
    fssaiNumber: "FSSAI-INSP-2026-8890",
    verified: true,
  },
  ADMIN: {
    id: "user-admin-01",
    name: "Farm Tracer System Administrator",
    organization: "Farm Tracer Platform HQ",
    email: "admin@farmtracer.app",
    phone: "+91 20 2780 1000",
    role: "ADMIN",
    address: "National Agricultural Tech Center, Pune",
    district: "Pune",
    state: "Maharashtra",
    pinCode: "411007",
    verified: true,
  },
  COLD_STORAGE: {
    id: "user-coldstorage-01",
    name: "Gokul Chilling Center",
    organization: "Gokul Milk Cold Chain Hub",
    email: "coldstorage@gokulmilk.co.in",
    phone: "+91 98220 99000",
    role: "COLD_STORAGE",
    address: "Karveer Chilling Plant, Kolhapur",
    district: "Kolhapur",
    state: "Maharashtra",
    pinCode: "416001",
    fssaiNumber: "11518012000456",
    verified: true,
  },
};

export function getDefaultProfile(role: UserRole): UserProfile {
  return DEFAULT_PROFILES[role] || DEFAULT_PROFILES.FARMER;
}
